import "../global.css";
import { Header } from '@widgets/header';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function HomeLayout({
		 children,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<main>
			<Header />
			{children}
		</main>
	);
}
