import '../global.css';

import { Header } from '@widgets/header';
import { hasLocale } from 'use-intl';
import { routing } from '@shared/lib/i18n';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}

export default async function HomeLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	// Func that allows NextIntl to detect the current locale in server components
	setRequestLocale(locale);

	return (
		<main>
			<NextIntlClientProvider>
				<Header />
				{children}
			</NextIntlClientProvider>
		</main>
	);
}
