import '../global.css';

import { setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { hasLocale } from 'use-intl';

import { routing } from '@shared/lib/i18n';
import { Header } from '@widgets/header';
import { ClientProviders, ServerProviders } from './providers';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}

export default async function HomeLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	// Func that allows NextIntl to detect the current locale in server components
	setRequestLocale(locale);

	return (
		<main>
			<ServerProviders>
				<ClientProviders>
					<Header />
					{children}
				</ClientProviders>
			</ServerProviders>
		</main>
	);
}
