import '../global.css';

import { Header } from '@widgets/header';
import { hasLocale } from 'use-intl';
import { routing } from '@shared/lib';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default async function HomeLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

if (!hasLocale(routing.locales, locale)) {
	notFound();
}

	return (
		<main>
			<NextIntlClientProvider>
				<Header />
				{children}
			</NextIntlClientProvider>
		</main>
	);
}
